package com.shelfie.core.media

/**
 * Deciding whether an image is a screenshot.
 *
 * There is no reliable system flag for this before very recent Android
 * versions, and OEMs disagree about where screenshots live:
 *
 *   Pixel/AOSP  Pictures/Screenshots  or  DCIM/Screenshots
 *   Samsung     DCIM/Screenshots
 *   Xiaomi      DCIM/Screenshots  and  MIUI/Gallery
 *   OnePlus     Pictures/Screenshots
 *   realme/oppo Pictures/Screenshots, sometimes "ScreenCapture"
 *   vivo        Pictures/Screenshot  (singular)
 *
 * So path matching is deliberately permissive, and a dimension check acts as a
 * secondary signal for files that live somewhere unexpected.
 *
 * Pure functions with no Android dependencies, so all of this is unit-testable.
 */
object ScreenshotHeuristics {

    private val PATH_KEYWORDS = listOf(
        "screenshot",
        "screenshots",
        "screencapture",
        "screen_capture",
        "screen-capture",
        "screencap",
    )

    private val FILENAME_KEYWORDS = listOf(
        "screenshot",
        "screen_",
        "screencap",
        "scrnshot",
    )

    /** True when the file's folder clearly marks it as a screenshot. */
    fun isScreenshotPath(relativePath: String?): Boolean {
        val normalised = relativePath?.lowercase()?.replace('\\', '/') ?: return false
        return PATH_KEYWORDS.any { keyword ->
            normalised.split('/').any { segment -> segment == keyword || segment.startsWith(keyword) }
        }
    }

    /** True when the filename looks generated by a screenshot tool. */
    fun isScreenshotFilename(displayName: String?): Boolean {
        val normalised = displayName?.lowercase() ?: return false
        return FILENAME_KEYWORDS.any { normalised.startsWith(it) || normalised.contains(it) }
    }

    /**
     * True when the image's dimensions match the display almost exactly.
     *
     * Used only as a fallback signal. [tolerancePx] absorbs the difference
     * between a full-screen capture and one that excludes the status bar or
     * navigation bar.
     */
    fun matchesDisplaySize(
        imageWidth: Int,
        imageHeight: Int,
        displayWidth: Int,
        displayHeight: Int,
        tolerancePx: Int = 240,
    ): Boolean {
        if (imageWidth <= 0 || imageHeight <= 0) return false
        if (displayWidth <= 0 || displayHeight <= 0) return false

        // Compare in both orientations — landscape screenshots are still screenshots.
        val portraitMatch = withinTolerance(imageWidth, displayWidth, tolerancePx) &&
            withinTolerance(imageHeight, displayHeight, tolerancePx)
        val landscapeMatch = withinTolerance(imageWidth, displayHeight, tolerancePx) &&
            withinTolerance(imageHeight, displayWidth, tolerancePx)

        return portraitMatch || landscapeMatch
    }

    /**
     * Combined decision. Path or filename evidence is sufficient on its own;
     * the dimension check only rescues files stored in an unusual location.
     */
    fun isLikelyScreenshot(
        relativePath: String?,
        displayName: String?,
        imageWidth: Int,
        imageHeight: Int,
        displayWidth: Int,
        displayHeight: Int,
    ): Boolean = when {
        isScreenshotPath(relativePath) -> true
        isScreenshotFilename(displayName) -> true
        else -> matchesDisplaySize(imageWidth, imageHeight, displayWidth, displayHeight)
    }

    private fun withinTolerance(actual: Int, expected: Int, tolerance: Int): Boolean =
        kotlin.math.abs(actual - expected) <= tolerance
}
